//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientAdmin.AdminLib {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminLib.IAdminCommands")]
    public interface IAdminCommands {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminCommands/updateCacheDurationCitites", ReplyAction="http://tempuri.org/IAdminCommands/updateCacheDurationCititesResponse")]
        string updateCacheDurationCitites(int duration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminCommands/updateCacheDurationCitites", ReplyAction="http://tempuri.org/IAdminCommands/updateCacheDurationCititesResponse")]
        System.Threading.Tasks.Task<string> updateCacheDurationCititesAsync(int duration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminCommands/updateCacheDurationStations", ReplyAction="http://tempuri.org/IAdminCommands/updateCacheDurationStationsResponse")]
        string updateCacheDurationStations(int duration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminCommands/updateCacheDurationStations", ReplyAction="http://tempuri.org/IAdminCommands/updateCacheDurationStationsResponse")]
        System.Threading.Tasks.Task<string> updateCacheDurationStationsAsync(int duration);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminCommandsChannel : ClientAdmin.AdminLib.IAdminCommands, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminCommandsClient : System.ServiceModel.ClientBase<ClientAdmin.AdminLib.IAdminCommands>, ClientAdmin.AdminLib.IAdminCommands {
        
        public AdminCommandsClient() {
        }
        
        public AdminCommandsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminCommandsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminCommandsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminCommandsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string updateCacheDurationCitites(int duration) {
            return base.Channel.updateCacheDurationCitites(duration);
        }
        
        public System.Threading.Tasks.Task<string> updateCacheDurationCititesAsync(int duration) {
            return base.Channel.updateCacheDurationCititesAsync(duration);
        }
        
        public string updateCacheDurationStations(int duration) {
            return base.Channel.updateCacheDurationStations(duration);
        }
        
        public System.Threading.Tasks.Task<string> updateCacheDurationStationsAsync(int duration) {
            return base.Channel.updateCacheDurationStationsAsync(duration);
        }
    }
}
