//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientConsole.JCDLibrary {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JCDLibrary.IVelibsRetriever")]
    public interface IVelibsRetriever {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsRetriever/getCities", ReplyAction="http://tempuri.org/IVelibsRetriever/getCitiesResponse")]
        string getCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsRetriever/getCities", ReplyAction="http://tempuri.org/IVelibsRetriever/getCitiesResponse")]
        System.Threading.Tasks.Task<string> getCitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsRetriever/getDataFromCity", ReplyAction="http://tempuri.org/IVelibsRetriever/getDataFromCityResponse")]
        string getDataFromCity(string city, string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibsRetriever/getDataFromCity", ReplyAction="http://tempuri.org/IVelibsRetriever/getDataFromCityResponse")]
        System.Threading.Tasks.Task<string> getDataFromCityAsync(string city, string station);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibsRetrieverChannel : ClientConsole.JCDLibrary.IVelibsRetriever, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibsRetrieverClient : System.ServiceModel.ClientBase<ClientConsole.JCDLibrary.IVelibsRetriever>, ClientConsole.JCDLibrary.IVelibsRetriever {
        
        public VelibsRetrieverClient() {
        }
        
        public VelibsRetrieverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VelibsRetrieverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibsRetrieverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibsRetrieverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getCities() {
            return base.Channel.getCities();
        }
        
        public System.Threading.Tasks.Task<string> getCitiesAsync() {
            return base.Channel.getCitiesAsync();
        }
        
        public string getDataFromCity(string city, string station) {
            return base.Channel.getDataFromCity(city, station);
        }
        
        public System.Threading.Tasks.Task<string> getDataFromCityAsync(string city, string station) {
            return base.Channel.getDataFromCityAsync(city, station);
        }
    }
}
